export enum EnrollmentStatus {
  ENROLLED = 'ENROLLED',
  DROPPED = 'DROPPED',
  COMPLETED = 'COMPLETED',
  TRANSFERRED = 'TRANSFERRED',
  SUSPENDED = 'SUSPENDED'
}

export enum PeriodStatus {
  PLANNED = 'PLANNED',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

export enum PeriodType {
  SEMESTER = 'SEMESTER',
  TRIMESTER = 'TRIMESTER',
  QUARTER = 'QUARTER',
  ANNUAL = 'ANNUAL',
  SUMMER = 'SUMMER',
  INTENSIVE = 'INTENSIVE'
}
