export enum GradeStatus {
  PENDING = 'PENDING',
  GRADED = 'GRADED',
  REVIEW_REQUESTED = 'REVIEW_REQUESTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  FINAL = 'FINAL',
  APPEALED = 'APPEALED'
}

export enum QualitativeGrade {
  EXCELLENT = 'EXCELLENT',
  GOOD = 'GOOD',
  SATISFACTORY = 'SATISFACTORY',
  NEEDS_IMPROVEMENT = 'NEEDS_IMPROVEMENT',
  UNSATISFACTORY = 'UNSATISFACTORY'
}
